version: '3'

services:
  mailstorage:
    restart: always
    image: guenterbailey/mailstorage:latest
    environment:
      - MYHOSTNAME=imap.archiv.local
      - MYDOMAIN=archiv.local
      - MESSAGE_SIZE_LIMIT=10485760
      - MAILBOX_SIZE_LIMIT=1073741824
    networks:
      - mailbackend
    volumes:
      - my_mailstorage:/home
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "567:567"

networks:
  mailbackend:

volumes:
  my_mailstorage:
