############################################################
# Dockerfile to create MySQL Server on Debian 8 jessie
############################################################

FROM debian:jessie
MAINTAINER <office@bailey-solution.com>

#update and install PostgreSQL with autopostgrebackup
RUN apt-get update && apt-get install -y mysql-server mysql-server-5.5 

#
# example Dockerfile for https://docs.docker.com/examples/postgresql_service/
#
